/**
 * API Schema Gate Hook
 *
 * Purpose: Ensure no one manually modifies moyan-api auto-generated API type definition files
 *
 * Iron Rule: No manual modification of src/apis/schemas.ts files
 *
 * Checks:
 * 1. Check if git diff contains schemas.ts file modifications
 * 2. If found, check for ApiExtraModels backend sync record
 * 3. Block commit if manual modification (non-moyan-api generated)
 *
 * @returns {Promise<HookResult>}
 */

import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';

interface HookResult {
  passed: boolean;
  message: string;
  warnings: string[];
  errors: string[];
  data?: {
    modifiedFiles: string[];
    apiSchemaFiles: string[];
  };
}

/**
 * 向上查找项目根目录（查找 package.json 文件）
 */
function findProjectRoot(): string {
  let currentDir = process.cwd();
  const maxDepth = 5;
  let depth = 0;

  while (depth < maxDepth) {
    if (fs.existsSync(path.join(currentDir, 'package.json'))) {
      return currentDir;
    }
    const parentDir = path.dirname(currentDir);
    if (parentDir === currentDir) {
      break;
    }
    currentDir = parentDir;
    depth++;
  }

  return process.cwd();
}

/**
 * 获取 git 暂存区的文件列表
 */
function getStagedFiles(): string[] {
  try {
    const output = execSync('git diff --cached --name-only', {
      encoding: 'utf-8',
      cwd: findProjectRoot()
    });
    return output.trim().split('\n').filter(Boolean);
  } catch (error) {
    // 如果没有暂存文件，返回空数组
    return [];
  }
}

/**
 * 获取工作区的修改文件列表
 */
function getWorkingDirChanges(): string[] {
  try {
    const output = execSync('git diff --name-only', {
      encoding: 'utf-8',
      cwd: findProjectRoot()
    });
    return output.trim().split('\n').filter(Boolean);
  } catch (error) {
    return [];
  }
}

/**
 * 检查文件是否是 API schemas 文件
 */
function isApiSchemaFile(filePath: string): boolean {
  // 匹配 src/apis/*/schemas.ts 或 packages/*/src/apis/*/schemas.ts
  const patterns = [
    /src\/apis\/[^/]+\/schemas\.ts$/,
    /packages\/[^/]+\/src\/apis\/[^/]+\/schemas\.ts$/,
  ];

  return patterns.some(pattern => pattern.test(filePath));
}

/**
 * 检查 schemas.ts 文件是否有 moyan-api 生成标记
 */
function hasMoyanApiMarker(filePath: string): boolean {
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    // 检查文件头部是否有自动生成标记
    const autoGeneratedMarkers = [
      /@generated/,
      /自动生成/,
      /moyan-api/,
      /DO NOT EDIT MANUALLY/,
    ];

    return autoGeneratedMarkers.some(marker => marker.test(content));
  } catch (error) {
    return false;
  }
}

/**
 * 检查是否有 api:build 执行记录
 */
function hasApiBuildRecord(): boolean {
  try {
    // 检查最近的 git commit message 中是否包含 api:build 相关记录
    const log = execSync('git log --oneline -5', {
      encoding: 'utf-8',
      cwd: findProjectRoot()
    });

    return /api:build|moyan-api|API 同步/i.test(log);
  } catch (error) {
    return false;
  }
}

const isMain = require.main === module;

if (isMain) {
  const projectRoot = findProjectRoot();

  // 获取暂存区和工作区的修改文件
  const stagedFiles = getStagedFiles();
  const workingDirChanges = getWorkingDirChanges();
  const allChanges = [...stagedFiles, ...workingDirChanges];

  // 筛选出 API schemas 文件
  const apiSchemaFiles = allChanges.filter(isApiSchemaFile);

  const result: HookResult = {
    passed: true,
    message: '✅ API 类型定义检查通过',
    warnings: [],
    errors: [],
    data: {
      modifiedFiles: allChanges,
      apiSchemaFiles: apiSchemaFiles
    }
  };

  // 如果修改了 API schemas 文件，进行详细检查
  if (apiSchemaFiles.length > 0) {
    for (const schemaFile of apiSchemaFiles) {
      const fullPath = path.join(projectRoot, schemaFile);

      // 检查是否有自动生成标记
      if (!hasMoyanApiMarker(fullPath)) {
        result.passed = false;
        result.errors.push(
          `Detected manual modification of API schema file: ${schemaFile}\n` +
          `Iron Rule: No manual modification of src/apis/*/schemas.ts files!\n\n` +
          `Correct workflow:\n` +
          `1. Confirm backend DTO has added fields + Swagger annotations\n` +
          `2. Backend adds @ApiExtraModels to register nested types (if needed)\n` +
          `3. Restart backend service to ensure Swagger docs are updated\n` +
          `4. Frontend runs pnpm api:build to auto-generate\n` +
          `5. Verify generated type definitions are correct\n\n` +
          `To modify API types, contact backend developers to improve Swagger docs and regenerate.`
        );
      }
    }

    if (result.passed) {
      result.warnings.push(
        `API schema files detected: ${apiSchemaFiles.join(', ')}\n` +
        `Please confirm these are auto-generated via pnpm api:build`
      );
    }
  }

  // Output results
  if (!result.passed) {
    result.message = 'API type definition check FAILED';
    console.error('\n' + '='.repeat(60));
    console.error(result.message);
    console.error('='.repeat(60));
    result.errors.forEach(err => console.error(err));
    console.error('='.repeat(60) + '\n');
    process.exit(1);
  } else {
    result.message = 'API type definition check PASSED';
    console.log(result.message);
    if (result.warnings.length > 0) {
      result.warnings.forEach(warn => console.log('WARNING: ' + warn));
    }
    process.exit(0);
  }
}
