packages:
  - packages/base-backend
  - packages/base-frontend
  - packages/extensions/*
  - packages/component-demo
  - packages/shared-dict
  - frontend
  - backend
  - examples
  - docs
  - .harness
  - business-dict

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - cypress
  - ejs
  - esbuild
  - unrs-resolver
  - vue-demi
