packages:
  - packages/base-backend
  - packages/base-frontend
  - packages/component-demo
  - frontend
  - examples
  - docs
  - .harness

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - cypress
  - ejs
  - esbuild
  - unrs-resolver
  - vue-demi
