packages:
  - packages/cli
  - packages/base/src/backend
  - packages/base/src/frontend
  - packages/base/src/shared
  - packages/extensions/*/src/backend
  - packages/extensions/*/src/frontend
  - packages/extensions/*/src/shared
  - packages/extensions/*
  - packages/base
  - packages/component-demo
  - frontend
  - backend
  - examples
  - docs
  - .harness
  - business-dict

catalog:
  '@element-plus/icons-vue': ^2.3.2
  '@nestjs/cli': ^10.4.9
  '@nestjs/common': ^10.4.22
  '@nestjs/config': ^3.3.0
  '@nestjs/core': ^10.4.22
  '@nestjs/jwt': ^10.2.0
  '@nestjs/platform-express': ^10.4.22
  '@nestjs/schematics': ^10.1.4
  '@nestjs/swagger': ^7.4.2
  '@nestjs/testing': ^10.4.9
  '@nestjs/typeorm': ^10.0.2
  '@types/bcrypt': ^5.0.2
  '@types/dotenv': ^8.2.3
  '@types/express': ^4.17.25
  '@types/jest': ^30.0.0
  '@types/multer': ^2.1.0
  '@types/node': ^22.19.15
  '@types/supertest': ^7.2.0
  '@vitejs/plugin-vue': ^5.2.4
  '@vitejs/plugin-vue-jsx': ^5.1.5
  '@vitest/coverage-v8': ^1.0.0
  '@vue/test-utils': ^2.4.10
  '@vueuse/core': ^14.2.1
  axios: ^1.6.5
  bcrypt: ^5.1.1
  class-transformer: ^0.5.1
  class-validator: ^0.14.4
  dotenv: ^17.3.1
  element-plus: ^2.13.5
  eslint: ^9.38.0
  jest: ^30.3.0
  jsdom: ^24.1.0
  md-editor-v3: ^6.4.2
  moyan-api: ^2.1.19
  multer: ^2.1.1
  mysql2: ^3.11.5
  pinia: ^2.3.0
  prettier: ^3.5.3
  quill: ^2.0.3
  redis: ^4.7.0
  reflect-metadata: ^0.1.14
  rxjs: ^7.8.2
  sass: ^1.70.0
  source-map-support: ^0.5.21
  supertest: ^7.2.2
  ts-jest: ^29.4.6
  ts-loader: ^9.4.3
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  tsc-alias: ^1.8.17
  tsx: ^4.21.0
  typeorm: ^0.3.28
  typescript: ^5.7.3
  vite: ^5.4.21
  vitest: ^1.6.1
  vue: ^3.5.30
  vue-advanced-cropper: ^2.8.8
  vue-router: ^4.5.1
  vue-tsc: ^2.2.12

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - cypress
  - ejs
  - esbuild
  - unrs-resolver
  - vue-demi
